### ISSUE TITLE
Using custom field in copy pattern

### ISSUE THREAD

**Issue by ddnguyen1494** [AndreyVMarkelov/copy-to-clipboard-jira-field#1]
Hi,

I'm trying to use a custom field called "Title" with ID 12126 in the copy pattern. I have tried $issue.Title, $issue.title, $issue.12126. 

What is the correct syntax for using custom field?

**Comment by AndreyVMarkelov** [comment]
@ddnguyen1494 With new version you can try:
```
#set($a2 = $customFieldManager.getCustomFieldObject("customfield_10001"))

$issue.getCustomFieldValue($a2)
```
