### ISSUE TITLE
quotation marks become &quot;

### ISSUE THREAD

**Issue by ddnguyen1494** [AndreyVMarkelov/copy-to-clipboard-jira-field#2]
When copying the Summary containing quotation marks (e.g "Parameters..."), the clipboard contains &quot;Parameters...&quot; instead. 

Is there any way to fix this or work around?

**Comment by AndreyVMarkelov** [comment]
Will fix. Thank you that found it

вт, 9 окт. 2018 г., 21:00 Daniel Nguyen <notifications@github.com>:

**Comment by AndreyVMarkelov** [comment]
Done
